version: "3.7"

services:
  {{SERVICE.LIGHTTPD.NAME}}_cert:
    image: sebp/lighttpd:latest
    container_name: {{SERVICE.LIGHTTPD.NAME}}_cert
    hostname: lighttpd.cert.{{SERVER.DOMAIN}}
    ports:
      - {{SERVICE.LIGHTTPD.PORTS.CERT_PORT}}:80
      # certificate file url:
      # http://<host>:<cert-server-port>/squid-proxy.pem
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Cert:/var/www/localhost/htdocs

  {{SERVICE.LIGHTTPD.NAME}}:
    build:
      context: .
    container_name: {{SERVICE.LIGHTTPD.NAME}}
    hostname: lighttpd.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{SERVICE.LIGHTTPD.PORTS.CACHING_PORT}}:{{SERVICE.LIGHTTPD.PORTS.CACHING_PORT}}
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Log:/var/log/squid
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Cache:/var/cache/squid
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Cert:/etc/squid/ssl_cert

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true



