version: "3.7"

services:
  {{SERVICE.LIGHTTPD.NAME}}:
    image: komlevv/caching-proxy:latest
    container_name: {{SERVICE.LIGHTTPD.NAME}}
    hostname: lighttpd.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{SERVICE.LIGHTTPD.PORTS.CACHING_PORT}}:{{SERVICE.LIGHTTPD.PORTS.CACHING_PORT}}
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Cache:/var/cache/squid
      - {{SERVER.SERVER_HOME}}/Server/Lighttpd/Log:/var/log/squid

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true



