version: "3.7"

services:
    {{SERVICE.SQUID.NAME}}:
      build:
        context: .
        args:
          - PROXY_PORT={{SERVICE.SQUID.PORTS.CACHING_PORT}}
          - PROXY_DOMAIN={{SERVER.DOMAIN}}
      container_name: {{SERVICE.SQUID.NAME}}
      hostname: squid.{{SERVER.DOMAIN}}
      restart: always
      ports:
        - {{SERVICE.SQUID.PORTS.CACHING_PORT}}:{{SERVICE.SQUID.PORTS.CACHING_PORT}}
      networks:
        - {{SERVICE.NETWORK.NAME}}
      volumes:
        - {{SERVER.SERVER_HOME}}/Server/Squid/Log:/var/log/squid
        - {{SERVER.SERVER_HOME}}/Server/Squid/Cache:/var/cache/squid
        - {{SERVER.SERVER_HOME}}/Server/Squid/Cert:/etc/squid/ssl_cert

networks:
    {{SERVICE.NETWORK.NAME}}:
      external: true



